ERROR:asyncio:Task exception was never retrieved
game-1            | future: <Task finished name='Task-376' coro=<AsyncServer._handle_event_internal() done, defined at /usr/local/lib/python3.13/site-packages/socketio/async_server.py:608> exception=TypeError("stop_moving() missing 1 required positional argument: 'data'")>
game-1            | Traceback (most recent call last):
game-1            |   File "/usr/local/lib/python3.13/site-packages/socketio/async_server.py", line 610, in _handle_event_internal
game-1            |     r = await server._trigger_event(data[0], namespace, sid, *data[1:])
game-1            |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
game-1            |   File "/usr/local/lib/python3.13/site-packages/socketio/async_server.py", line 637, in _trigger_event
game-1            |     ret = await handler(*args)
game-1            |                 ~~~~~~~^^^^^^^
game-1            | TypeError: stop_moving() missing 1 required positional argument: 'data'
